### ISSUE TITLE
Website linked in the description doesn't seem to load properly

### ISSUE THREAD

**Issue by notarock** [muety/anchr#60]
While looking for more information on this project, I stumbled upon this when I clicked on the website linked in the repository's description:

![image](https://user-images.githubusercontent.com/25652765/154127718-bef04eb5-d20a-4e75-ad64-07fab511dc21.png)

`Mozilla Firefox 97.0`

**Comment by muety** [comment]
That is weird, never saw that error message before on Anchr. Could be due to some ad-blocking add-on that you're using? Maybe try with a different browser or on a different machine to see if the problem persists. A while ago, anchr.io was added to some blocklists, because people were abusing Anchr's shortlink feature to link to phishing sites etc. Might well be that some anti-virus software or so on your computer is blocking Anchr for that reason.

**Comment by notarock** [comment]
> Could be due to some ad-blocking add-on that you're using?

Just to make sure it was not the ad blocker doing it's thing, I tried opening [anchr.io](https://anchr.io) in chromium with no extensions:

![image](https://user-images.githubusercontent.com/25652765/154300487-669d2566-e142-47dc-bb80-300b094c7715.png)

Same thing happens on both my computers... But when I try on mobile, I get redirected to safebrowse.io :thinking:

**Comment by muety** [comment]
Are you by chance using an ad-blocking DNS server? What IP does _anchr.io_ resolve to your you?

```bash
$ dig +short anchr.io
# or
$ nslookup anchr.io
```

**Comment by notarock** [comment]
```
$ nslookup anchr.io
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	anchr.io
Address: 164.68.116.134
Name:	anchr.io
Address: 2a02:c207:3004:2171::1
```
I just tried it on my phone over mobile network and it worked :thinking: It's weird because it didn't work on my local network...

> A while ago, anchr.io was added to some blocklists, because people were abusing Anchr's shortlink feature to link to phishing sites etc.

It could mean my ISP is potentially blocking the domain name from my understanding. In any case, I don't think there is much else to do :disappointed:

**Comment by muety** [comment]
That is really strange. I could have imagined your ISP's DNS resolvers to report deviating IPs for supposedly malicious domains, but the IP you posted is actually the correct one. That could mean they block / intercept the actual HTTP requests to IPs they consider evil. I'd be super interested to learn about what's going on there in the background and to find out how to get my IP off that blocklist. Maybe you can get details from your ISP? Of course, don't feel obliged to to put more effort than you want!
