### ISSUE TITLE
Unable to start production

### ISSUE THREAD

**Issue by ohitstom** [muety/anchr#64]
![image](https://user-images.githubusercontent.com/22730962/198854022-8e958627-767e-482d-8bee-9629002b7535.png)

**Comment by ohitstom** [comment]
![image](https://user-images.githubusercontent.com/22730962/198854541-a2c7979e-b1b4-4079-b845-d740f20b6135.png)
![image](https://user-images.githubusercontent.com/22730962/198854543-dfb1e8e9-f068-46a0-b16c-81f74d0433ac.png)

**Comment by ohitstom** [comment]
![image](https://user-images.githubusercontent.com/22730962/198855222-05bd67aa-1646-4974-88cd-c0c264368b28.png)
![image](https://user-images.githubusercontent.com/22730962/198855225-799b7110-5a17-491c-820e-2027f41eae59.png)

**Comment by muety** [comment]
Hey @ohitstom! Firstly, the command is `yarn production` instead of `yarn start production`, but I think that won't fix your issue. Did you make sure the environment variables are actually loaded, i.e. did you run the `env.bat` script?

**Comment by ohitstom** [comment]
> Hey @ohitstom! Firstly, the command is `yarn production` instead of `yarn start production`, but I think that won't fix your issue. Did you make sure the environment variables are actually loaded, i.e. did you run the `env.bat` script?

I did make sure to run the environment script yes, I'm really unsure why I can connect over mongo command line but not using yarn

**Comment by muety** [comment]
Must be some issues with your environment variables. In your screenshot, all connection parameters are `undefined`, so the app doesn't receive the env vars for some reason.

**Comment by ohitstom** [comment]
> Must be some issues with your environment variables. In your screenshot, all connection parameters are `undefined`, so the app doesn't receive the env vars for some reason.

Reference the images in my replied messages, I fixed that issue and still no dice
