### ISSUE TITLE
Run with Docker not working

### ISSUE THREAD

**Issue by gander** [muety/anchr#70]
The service starts, but you cannot connect to it, it rejects connections.

**Comment by muety** [comment]
How to you start the container? Using the provided Docker Compose file or via `docker run` with the plain image? In the latter case, you'll either have to set `LISTEN_ADDR=0.0.0.0` in your config file or pass it via `-e` to the `docker run` command. Hope that helps.

**Comment by HESOYAM-abuser** [comment]
The user of the database was not created befrore

I created the user by using mongo shell:
`sudo docker exec -it anchr_mongo_1 mongosh -u anchr -p 1234 `

how ever i want to do this in docker-compose.yml or DOCKERFILE
