### ISSUE TITLE
MongoServerError: Authentication failed

### ISSUE THREAD

**Issue by USFAkbari** [muety/anchr#74]
# MongoDB Server Error

#### I would be glad to assist you in resolving the error you are encountering. Please provide specific details about the error message or issue, including any relevant context or steps that led to its occurrence. This information will help me offer more targeted guidance to effectively address the problem.

**Comment by USFAkbari** [comment]
I Want to Use ` Anchr ` Locally on My Virtual Machine

**Comment by muety** [comment]
You'll need to create an `.env` file (possibly use `.env.example` as a template), choose a database password (and other config options) there (see [configuration](https://github.com/muety/anchr?tab=readme-ov-file#configuration)), then source the env file (see [here](https://github.com/muety/anchr?tab=readme-ov-file#option-2-run-with-docker)) and run the Docker compose.

**Comment by USFAkbari** [comment]
I completed all configurations, but I can't authenticate the user from Mongosh.

**Comment by USFAkbari** [comment]
I handle this error with edit Mongo script you can change .env argument to 
```
mongosh -u userAdmin -p userPassword --authenticationDatabase admin <<EOF
use $MONGO_INITDB_DATABASE;
db.createUser({
  user: "$DB_USER",
  pwd: "$DB_PASSWORD",
  roles: [
    {
      role: "dbOwner",
      db: "$MONGO_INITDB_DATABASE"
    }
  ]
});
EOF

```
I encountered a bug while using "Bower install" and a Dockerfile.
