### ISSUE TITLE
bower angular-jwt#*            ECMDERR Failed to execute 

### ISSUE THREAD

**Issue by USFAkbari** [muety/anchr#75]
```

bower angular-jwt#*         not-cached https://github.com/auth0/angular-jwt.git#*
bower angular-jwt#*            resolve https://github.com/auth0/angular-jwt.git#*
bower angular-jwt#*            ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/auth0/angular-jwt.git", exit code of #128 fatal: unable to access 'https://github.com/auth0/angular-jwt.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.

```
I encountered this specific error when I was working with the `bower install` command in the `public` folder of my project. After some troubleshooting, I decided to delete the `angular-jwt` dependency, which I thought might be causing the issue. Once I removed that dependency and ran the project again, it actually worked this time. However, I noticed that the result I got was different from what you had on your `anchor.io` site, which was a bit surprising to me.

I kindly ask you to take some time . Once you have completed your review, please get back to me with your thoughts or any feedback you may have.

**Comment by muety** [comment]
Well, you can't just arbitrarily delete dependency. Especially this one is required for authentication. The error looks like some temporary issue with GitHub to me. Or possibly your system is using some outdated TLS library? At least I can't reproduce the issue on my end. I ran `bower install` and it completed just fine.
